application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  license.accept:
    type: string
    title: EULA License
    description: Accept EULA license
    default: "no"
  cic.image:
    type: string
    default: $REGISTRY/citrix-k8s-ingress-controller:$TAG
    x-google-marketplace:
      type: IMAGE
  cic.required:
    type: boolean
    title: Citrix Ingress Controller
    description: Set if CIC is required for Citrix ADC CPX
    default: false
  cpx.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: ['services', 'endpoints', 'ingresses', 'pods', 'secrets', 'nodes']
            verbs: ['*']
          - apiGroups: ['extensions']
            resources: ['ingresses', 'ingresses/status']
            verbs: ['*']
          - apiGroups: ['citrix.com']
            resources: ['rewritepolicies']
            verbs: ['*']
          - apiGroups: ['apps']
            resources: ['deployments']
            verbs: ['*']
  logLevel:
    type: string
    title: Log level of Citrix ingress controller
    description: Level of logs generated by Citrix ingress controller
    default: DEBUG
  ingressClass:
    type: string
    title: Ingress Class
    description: Please provide name of the Ingress Class if needs to be supported by Citrix Ingress Controller.
  exporter.image:
    type: string
    default: $REGISTRY/netscaler-metrics-exporter:$TAG
    x-google-marketplace:
      type: IMAGE
  exporter.required:
    type: boolean
    title: Prometheus Exporter
    description: Set if exporter is needed with Citrix ADC CPX
    default: false
  exporter.ports.containerPort:
    type: integer
    title: Prometheus Exporter Port
    description: Specify on which port metrics collected by the exporter should be exposed.
    default: 8888

required:
- name
- namespace
- cpx.image
- cic.required
- cic.image
- serviceAccount
- exporter.required
- exporter.image
