apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "citrix-master-project", "product_id": "citrix-k8s-cpx-ingress-controller", "partner_name": "Citrix"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: CITRIX
    version: '121.51.16'
    description: |-
      People-centric solutions for a better way to work
    maintainers:
    - name: Citrix
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'CITRIX: Getting Started'
      url: https://www.citrix.com/
    notes: |-
      # Configuring CITRIX Controller
      Configuring CPX with CITRIX Ingress Controller running as side car.
  info:
  - name: Application Namespace
    value: {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Pod
  - group: apps/v1beta2
    kind: StatefulSet
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
